# Generated by Django 4.0.1 on 2022-03-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeID', models.IntegerField()),
                ('name', models.CharField(max_length=27)),
                ('description', models.TextField()),
                ('steps', models.TextField()),
            ],
        ),
    ]
