# Generated by Django 4.0.1 on 2022-03-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeportaldb', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientID', models.IntegerField(primary_key=True, serialize=False)),
                ('iName', models.CharField(max_length=255)),
                ('foodType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('utensilID', models.IntegerField(primary_key=True, serialize=False)),
                ('uName', models.CharField(default='00000', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cName',
            field=models.CharField(default='00000', max_length=255),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rName',
            field=models.CharField(default='00000', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='00000', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default='00000', max_length=255),
        ),
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('nutritionID', models.IntegerField(primary_key=True, serialize=False)),
                ('portionSize', models.FloatField(max_length=24)),
                ('calories', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('_ingredientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeportaldb.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='UtensilRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_recipeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeportaldb.recipe')),
                ('_utensilID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeportaldb.utensil')),
            ],
            options={
                'unique_together': {('_utensilID', '_recipeID')},
            },
        ),
        migrations.CreateModel(
            name='IngredientRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255)),
                ('_ingredientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeportaldb.ingredient')),
                ('_recipeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeportaldb.recipe')),
            ],
            options={
                'unique_together': {('_ingredientID', '_recipeID')},
            },
        ),
        migrations.CreateModel(
            name='CategoryRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_categoryID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipeportaldb.category')),
                ('_recipeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipeportaldb.recipe')),
            ],
            options={
                'unique_together': {('_categoryID', '_recipeID')},
            },
        ),
    ]
