# Generated by Django 4.0.1 on 2022-03-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeportaldb', '0003_ingredient_utensil_remove_category_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryID',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='categoryrecipe',
            old_name='_categoryID',
            new_name='categoryid',
        ),
        migrations.RenameField(
            model_name='categoryrecipe',
            old_name='_recipeID',
            new_name='recipeid',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientID',
            new_name='ingredientid',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='foodType',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='iName',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='ingredientnutrition',
            old_name='_ingredientID',
            new_name='ingredientid',
        ),
        migrations.RenameField(
            model_name='ingredientnutrition',
            old_name='nutritionID',
            new_name='nutritionid',
        ),
        migrations.RenameField(
            model_name='ingredientnutrition',
            old_name='portionSize',
            new_name='portionsize',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='_ingredientID',
            new_name='ingredientid',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='_recipeID',
            new_name='recipeid',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='rName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipeID',
            new_name='recipeid',
        ),
        migrations.RenameField(
            model_name='utensil',
            old_name='uName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='utensil',
            old_name='utensilID',
            new_name='utensilid',
        ),
        migrations.RenameField(
            model_name='utensilrecipe',
            old_name='_recipeID',
            new_name='recipeid',
        ),
        migrations.RenameField(
            model_name='utensilrecipe',
            old_name='_utensilID',
            new_name='utensilid',
        ),
        migrations.AlterUniqueTogether(
            name='categoryrecipe',
            unique_together={('categoryid', 'recipeid')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredientnutrition',
            unique_together={('nutritionid', 'ingredientid')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredientrecipe',
            unique_together={('ingredientid', 'recipeid')},
        ),
        migrations.AlterUniqueTogether(
            name='utensilrecipe',
            unique_together={('utensilid', 'recipeid')},
        ),
    ]
